project:
  type: book
  output-dir: docs
  
book:
  title: "🐍 PySchool"
  author: "Python Chile"
  date: "08/20/2024"
  favicon: "images/pc.png"
  chapters:
    - index.qmd
    - talleres/intro_progra.qmd
    - talleres/taller_1/taller_1.qmd
    - talleres/taller_2A/taller_2A.qmd
    - talleres/taller_2C/taller_2C.qmd

lang: es

format:
  html:
    theme: flatly
  epub:
    cover-image: images/cover.png

filters: 
  - pyodide