project:
  type: book
  output-dir: docs
  
book:
  title: "🐍 PySchool"
  author: "Python Chile"
  date: "08/20/2024"
  favicon: "images/pc.png"
  chapters:
    - index.qmd
    - part: prefacio/intro.qmd
      chapters:
        - prefacio/intro_progra.qmd
        - prefacio/intro_python.qmd
    - part: talleres/intro.qmd
      chapters:
        - talleres/taller_1.qmd
        - talleres/taller_2.qmd
        - talleres/taller_3.qmd

index:
  qmd:
lang: es

format:
  html:
    theme: flatly
    number-sections: false
  epub:
    cover-image: images/cover.png


filters: 
  - pyodide

sin-enumeracion: true  # Esta línea es opcional para indicar que no se desea enumeración
